name: CI

on: push

jobs:
  shared-workflow:
    uses: scribd/github-actions-shared-workflows/.github/workflows/shared-workflow.yml@main
    secrets:
      github_access_token: ${{ secrets.SCRIBD_GITHUB_GENERIC_TOKEN }}
